# Generated by Django 4.2 on 2025-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('weather', models.CharField(max_length=255, verbose_name='天気')),
                ('condition', models.IntegerField(default=0, verbose_name='体調')),
                ('feeling', models.IntegerField(default=0, verbose_name='気分')),
            ],
            options={
                'db_table': 'diaries',
            },
        ),
    ]
