# Generated by Django 4.2 on 2025-07-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='feeling',
        ),
    ]
