# Generated by Django 4.2 on 2025-07-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diary_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='feeling',
            field=models.IntegerField(default=0, verbose_name='気分'),
        ),
    ]
