# Generated by Django 4.2 on 2025-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.TextField(max_length=255, verbose_name='天気'),
        ),
    ]
