# Generated by Django 4.2 on 2025-07-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.CharField(max_length=255, verbose_name='天気'),
        ),
    ]
