# Generated by Django 4.2 on 2025-07-25 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_diary_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='condition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='体調'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='気分'),
        ),
    ]
