# Generated by Django 4.2 on 2025-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_diary_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='condition',
            field=models.CharField(choices=[('good', '良い'), ('normal', '普通'), ('bad', '悪い')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.CharField(choices=[('good', '良い'), ('normal', '普通'), ('bad', '悪い')], max_length=10),
        ),
    ]
